save_dir: "output"
wandb:
  project: "Jigmentation"
  mode: "online"
  name: "CLUSTER_pos1.0_swav1.0_cosine100_tp0.1"
  notes: ""

# ---------------------------------------------------------------- #
seed: 10
num_classes: 27
dataset_name: "cocostuff27"
data_dir: "../Datasets/cocostuff"

# ---------------------------------------------------------------- #
resume:
  checkpoint: null
# ---------------------------------------------------------------- #
model:
  pretrained:
    model_type: "vit_small"
    dino_patch_size: 8
    freeze_backbone: true # default true
    drop_prob: 0.1
    pretrained_weights: null
    dropout: false
  enc_num_blocks: 1
  semantic_dim: 512
  hidden_dim: 512
  last_norm: false
  agg_type: "concat"
  k_means:
    init: "k-means++"
    n_cluster: 64
    n_pos: 16

# ---------------------------------------------------------------- #
loss:
  info_nce_weight: 1.0
  swav_weight : 1.0
  info_nce:
    neg_sample: 100
    temperature: 0.1
    normalize: "l2"
    cal_type: "cosine" # "random", "cosine", "distance"

  cluster :
    num_prototypes : 128 # TODO check
    queue_start_iter : 0 # TODO check
    queue_stack_iter : 5
    temperature : 0.1
    eps : 0.05 # TODO check

# ---------------------------------------------------------------- #
dataset:
  train:
    data_dir: ${data_dir}
    dataset_name: ${dataset_name}
    crop_type: null # "five" # null
    crop_ratio: 0.5
    loader_crop_type: "center"
    res: 224        # 224, 320
  val:
    data_dir: ${data_dir}
    dataset_name: ${dataset_name}
    crop_type: null
    loader_crop_type: "center"  # none for voc
    res: 320

dataloader:
  train:
    batch_size: 64  # total
    num_workers: 8  # total
  val:
    batch_size: 32  # total
    num_workers: 8  # total

# ---------------------------------------------------------------- #
optimizer:
  model:
    name: "adamw"
    lr: 5.0e-7
    weight_decay: 1e-4
  cluster:
    name: "adam"
    lr: 3.0e-3
  linear:
    name: "adam"
    lr: 3.0e-3

# ---------------------------------------------------------------- #
scheduler:
  model:
    name: "constant" # cos, constant
  cluster:
    name: "constant"
  linear:
    name: "constant"

# ---------------------------------------------------------------- #
eval:
  extra_classes: 0

# ---------------------------------------------------------------- #
train:
  max_epochs: 10
  print_interval_iters: 25
  valid_interval_iters: 25
  clip_grad: 1.0
  num_accum: 1