save_dir: "output"
wandb:
  project: "Jigmentation"
  mode: "online"
  name: "VAE_ex3_kernel1"
  notes: "PQ_1024_1024_contrast10.0_pq(1, 16)"

# ---------------------------------------------------------------- #
seed: 10
num_classes: 27
dataset_name: "cocostuff27"
data_dir: "../Datasets/cocostuff"

# ---------------------------------------------------------------- #
resume:
  checkpoint: null
# ---------------------------------------------------------------- #
model:
  pretrained:
    model_type: "vit_small"
    dino_patch_size: 8
    freeze_backbone: true
    drop_prob: 0.1
    pretrained_weights: null
    dropout: false
  enc_num_blocks: 1
  dec_num_blocks: 1
  hidden_dim: 384
  last_norm: false
  vq:
    vq_type: "ema"  # ema, param
    num_codebooks: [ 1024,  1024 ]
    embed_dims: [ 512,  512 ]
    beta: 0.25
    normalize: "l2"  # l2, z_norm, z_trainable, none
    use_restart: false
    use_split: true
    use_gumbel: false
    use_weighted_sum: false
    update_norm: true # check
    decay: 0.99
    eps: 1.0e-5
    num_pq: [ 4, 16 ]
    agg_type: "concat"  # add, concat


# ---------------------------------------------------------------- #
loss:
  recon_weight: 1.0
  vq_weight: 10.0
  contra_weight: 0.0

# ---------------------------------------------------------------- #
dataset:
  train:
    data_dir: ${data_dir}
    dataset_name: ${dataset_name}
    crop_type: "five"
    crop_ratio: 0.5
    loader_crop_type: "center"
    res: 224
  val:
    data_dir: ${data_dir}
    dataset_name: ${dataset_name}
    crop_type: null
    loader_crop_type: "center"  # none for voc
    res: 320

dataloader:
  train:
    batch_size: 64  # total
    num_workers: 4  # total
  val:
    batch_size: 32  # total
    num_workers: 4  # total

# ---------------------------------------------------------------- #
optimizer:
  model:
    name: "adamw"
    lr: 3.0e-4
    weight_decay: 2.0
  cluster:
    name: "adam"
    lr: 3.0e-3
  linear:
    name: "adam"
    lr: 3.0e-3

# ---------------------------------------------------------------- #
scheduler:
  model:
    name: "cos"
  cluster:
    name: "cos"
  linear:
    name: "cos"

# ---------------------------------------------------------------- #
eval:
  output_type: "vq0" # feat, vq0
  extra_classes: 0

# ---------------------------------------------------------------- #
train:
  max_epochs: 10
  print_interval_iters: 25
  valid_interval_iters: 100
  clip_grad: 1.0
  num_accum: 2