save_dir: "output"
wandb:
  project: "Jigmentation"
  mode: "online"
  name: "PQGO_baseline_stego_reproduced_128"
  notes: "1024-512"

# ---------------------------------------------------------------- #
seed: 10
num_classes: 27
dataset_name: "cocostuff27"
data_dir: "../Datasets/cocostuff"
is_visualize: false                           # default false, true
visualize_path: "./visualize/jsd1.0/crf/"
# ---------------------------------------------------------------- #
resume:
  checkpoint: null                          # default null

# ---------------------------------------------------------------- #
model:
  pretrained:
    model_type: "vit_small"
    dino_patch_size: 8
    freeze_backbone: true
    drop_prob: 0.1
    pretrained_weights: null
    dropout: false
  enc_num_blocks: 1
  dec_num_blocks: 3
  last_norm: false
  vq:
    vq_type: "param"                          # "ema", "param"
    num_codebooks: [ 512 ] # 512
    embed_dims: [ 128 ]
    beta: 0.25
    normalize: "l2"                           # l2, z_norm, z_trainable, none
    use_restart: false                        # default false, true
    use_weighted_sum: false                   # default false, true
    need_initialized: "uni"                   # default none : kmeans, uni, normal, rand
    pq_dropout: 0.0                         # defulat(ratio of pq mask) : 0.0,
    decay: 0.99
    eps: 1.0e-5
    num_pq: [ 32 ]             # 64               # 1 for vq
    agg_type: "concat"                        # add, concat
    n_kmeans: 8
    use_kmeans_sampling: false                # default false, true

# ---------------------------------------------------------------- #
loss:
  stego_weight : 1.0
  recon_weight: 0.0
  vq_weight: 0.0
  info_nce_weight: 0.0
  jsd_weight: 0.0
  margin_weight: 0.0

  info_nce:
    normalize: "l2"
    neg_sample: 10                           # TODO need check
    temperature: 1.0                          # TODO need check
    cal_type: "cosine"                      # TODO need check "distance" "cosine" "random"
  jsd:
    temperature: 1.0
    entropy_weight: 0.01
  stego:
    neg_inter_weight: 0.63
    pos_inter_weight: 0.25
    pos_intra_weight: 0.67
    neg_inter_shift: 0.66
    pos_inter_shift: 0.02
    pos_intra_shift: 0.08
    zero_clamp: true
    pointwise: true
    stabilize: false
    feature_samples: 11
    neg_samples: 5


# ---------------------------------------------------------------- #
dataset:
  train:
    data_dir: ${data_dir}
    dataset_name: ${dataset_name}
    crop_type: "five" # null, "five"
    crop_ratio: 0.5
    loader_crop_type: "center"
    num_neighbors : 7
    res: 224
  val:
    data_dir: ${data_dir}
    dataset_name: ${dataset_name}
    crop_type: null
    loader_crop_type: "center"                # none for voc
    res: 320

dataloader:
  train:
    batch_size: 32  # total
    num_workers: 8  # total
  val:
    batch_size: 16  # total
    num_workers: 8  # total

# ---------------------------------------------------------------- #
optimizer:
  model:
    name: "adamw"
    lr: 5.0e-4
    weight_decay: 0.0
  cluster:
    name: "adam"
    lr: 5.0e-3
  linear:
    name: "adam"
    lr: 5.0e-3

# ---------------------------------------------------------------- #
scheduler:
  model:
    name: "constant"  # default "constant", "cos",
  cluster:
    name: "constant"
  linear:
    name: "constant"

# ---------------------------------------------------------------- #
eval:
  output_type: "feat" # TODO chagned to vq0 -> for vq
  extra_classes: 0

# ---------------------------------------------------------------- #
train:
  max_epochs: 3
  print_interval_iters: 25
  valid_interval_iters: 100
  clip_grad: 1.0      # default 1.0
  num_accum: 1