save_dir: "output"
wandb:
  project: "Jigmentation"
  mode: "online"
  name: "RES_baseline_pos0.1_neg0.001_iter5_distance5_gau0.01_residual"
  notes: ""

# ---------------------------------------------------------------- #
seed: 10
num_classes: 27
dataset_name: "cocostuff27"
data_dir: "../Datasets/cocostuff"

# ---------------------------------------------------------------- #
resume:
  checkpoint: null
# ---------------------------------------------------------------- #
model:
  pretrained:
    model_type: "vit_small"
    dino_patch_size: 8
    freeze_backbone: true
    drop_prob: 0.1
    pretrained_weights: null
    dropout: false
  enc_num_blocks: 1
  dec_num_blocks: 3
  semantic_dim: 512
  local_dim: 512
  hidden_dim: 512
  last_norm: false
  agg_type: "concat"

# ---------------------------------------------------------------- #
loss:
  recon_weight: 1.0
  info_nce_weight: 0.1
  club_weight: 0.001

  info_nce:
    neg_sample: 5
    temperature: 1.0
    normalize: "l2"
    cal_type: "distance" # "random", "point", "distance"
  club:
    mi_iter : 5
    clip_grad : 1.0
# ---------------------------------------------------------------- #
dataset:
  train:
    data_dir: ${data_dir}
    dataset_name: ${dataset_name}
    crop_type: null # "five" # , null
    crop_ratio: 0.5
    loader_crop_type: "center"
    res: 224
  val:
    data_dir: ${data_dir}
    dataset_name: ${dataset_name}
    crop_type: null
    loader_crop_type: "center"  # none for voc
    res: 320

dataloader:
  train:
    batch_size: 16  # total
    num_workers: 8  # total
  val:
    batch_size: 16  # total
    num_workers: 8  # total

# ---------------------------------------------------------------- #
optimizer:
  model:
    name: "adamw"
    lr: 1.0e-5
    weight_decay: 1.0e-4
  club_enc:
    name: "adam"
    lr: 3.0e-6
    weight_decay: 0.0
  cluster:
    name: "adam"
    lr: 3.0e-3
  linear:
    name: "adam"
    lr: 3.0e-3

# ---------------------------------------------------------------- #
scheduler:
  model:
    name: "cos" # cos, constant
  club_enc:
    name: "constant"
  cluster:
    name: "cos"
  linear:
    name: "cos"

# ---------------------------------------------------------------- #
eval:
  extra_classes: 0

# ---------------------------------------------------------------- #
train:
  max_epochs: 10
  print_interval_iters: 25
  valid_interval_iters: 25
  clip_grad: 1.0
  num_accum: 1