save_dir: "output"
wandb:
  project: "Jigmentation"
  mode: "online"
  name: "RES_baseline_lr"
  notes: "only_enc_dec, no_contrast, no_mi"

# ---------------------------------------------------------------- #
seed: 10
num_classes: 27
dataset_name: "cocostuff27"
data_dir: "../Datasets/cocostuff"

# ---------------------------------------------------------------- #
resume:
  checkpoint: null
# ---------------------------------------------------------------- #
model:
  pretrained:
    model_type: "vit_small"
    dino_patch_size: 8
    freeze_backbone: true
    drop_prob: 0.1
    pretrained_weights: null
    dropout: false
  enc_num_blocks: 1
  dec_num_blocks: 3
  hidden_dim: 512
  last_norm: false
  agg_type: "concat"


# ---------------------------------------------------------------- #
loss:
  recon_weight: 1.0
  contra_weight:
    pos: 0.0
    neg: 0.0

# ---------------------------------------------------------------- #
dataset:
  train:
    data_dir: ${data_dir}
    dataset_name: ${dataset_name}
    crop_type: "five"
    crop_ratio: 0.5
    loader_crop_type: "center"
    res: 224
  val:
    data_dir: ${data_dir}
    dataset_name: ${dataset_name}
    crop_type: null
    loader_crop_type: "center"  # none for voc
    res: 320

dataloader:
  train:
    batch_size: 128  # total
    num_workers: 8  # total
  val:
    batch_size: 64  # total
    num_workers: 8  # total

# ---------------------------------------------------------------- #
optimizer:
  model:
    name: "sgd"
    lr: 3.0e-2
    weight_decay: 1.0e-4
  cluster:
    name: "sgd"
    lr: 3.0e-1
  linear:
    name: "sgd"
    lr: 3.0e-1

# ---------------------------------------------------------------- #
scheduler:
  model:
    name: "cos" # cos, constant
  cluster:
    name: "cos"
  linear:
    name: "cos"

# ---------------------------------------------------------------- #
eval:
  extra_classes: 0

# ---------------------------------------------------------------- #
train:
  max_epochs: 2
  print_interval_iters: 25
  valid_interval_iters: 25
  clip_grad: 1.0
  num_accum: 1