save_dir: "output"
wandb:
  project: "Jigmentation"
  mode: "online"
  name: "STEGO_potsdam_small_reproduced"
  notes: ""
  tags_dataset: ${dataset_name}
  tags_model: ${model.pretrained.model_type}

# ---------------------------------------------------------------- #
seed: 10
num_classes: 3                              # TODO need to fix per dataset
dataset_name: "potsdam"                     # "potsdam", "cityscape", "cocostuff27"
data_dir: "../Datasets/potsdam"
is_visualize: false                           # default false, true
visualize_path: "./visualize/"
# ---------------------------------------------------------------- #
resume:
  checkpoint: null
# ---------------------------------------------------------------- #
model:
  pretrained:
    model_type: "vit_small"
    dino_patch_size: 8
    freeze_backbone: true
    drop_prob: 0.1
    pretrained_weights: null
    dropout: true
    dim : 70


# ---------------------------------------------------------------- #
loss:
  stego_weight: 1.0
  # cocostuff27 with vit-small
#  neg_inter_weight: 0.63
#  pos_inter_weight: 0.25
#  pos_intra_weight: 0.67
#  neg_inter_shift: 0.66
#  pos_inter_shift: 0.02
#  pos_intra_shift: 0.08

  # cocostuff27 with vit-base
#  neg_inter_weight: 0.1538476246415498
#  neg_inter_weight: 0.15
#  pos_inter_weight: 1
#  pos_intra_weight: 0.1
#  neg_inter_shift: 1
#  pos_inter_shift: 0.2
#  pos_intra_shift: 0.12

  # cityscape with vit-base
#  neg_inter_weight: 0.91
#  pos_inter_weight: 0.58
#  pos_intra_weight: 1.00
#  neg_inter_shift: 0.31
#  pos_inter_shift: 0.18
#  pos_intra_shift: 0.46

  # potsdam with vit-small
  neg_inter_weight: 0.63
  pos_inter_weight: 0.25
  pos_intra_weight: 0.67
  neg_inter_shift: 0.46
  pos_inter_shift: 0.02
  pos_intra_shift: 0.08

  zero_clamp: true
  pointwise: true
  stabilize: false
  feature_samples: 11
  neg_samples: 5

# ---------------------------------------------------------------- #
dataset:
  train:
    data_dir: ${data_dir}
    dataset_name: ${dataset_name}
    model_type : ${model.pretrained.model_type}
    crop_type: "five"
    crop_ratio: 0.5
    loader_crop_type: "center"
    num_neighbors: 7
    res: 224
  val:
    data_dir: ${data_dir}
    dataset_name: ${dataset_name}
    model_type : ${model.pretrained.model_type}
    crop_type: null
    loader_crop_type: "center"  # none for voc
    res: 320

dataloader:
  train:
    batch_size: 32  # total
    num_workers: 8  # total
  val:
    batch_size: 16  # total
    num_workers: 8  # total
    is_visualize: ${is_visualize}

# ---------------------------------------------------------------- #
optimizer:
  model:
    name: "adam"
    lr: 5.0e-4
    weight_decay:
  cluster:
    name: "adam"
    lr: 5.0e-3
  linear:
    name: "adam"
    lr: 5.0e-3

# ---------------------------------------------------------------- #
scheduler:
  model:
    name: "constant"
  cluster:
    name: "constant"
  linear:
    name: "constant"

# ---------------------------------------------------------------- #
eval:
  extra_classes: 0

# ---------------------------------------------------------------- #
train:
  max_epochs: 1
  print_interval_iters: 25
  valid_interval_iters: 100
  clip_grad: 10.0
  num_accum: 1